# Example configuration for ros2_bag_utils rewrite_frame_id tool
input_bag: /path/to/original_bag
# output_bag: /path/to/output_bag  # Optional; if omitted a suffixed directory is created
mappings:
  /example/topic: base_link
  /another/topic: camera_link
